### ISSUE TITLE
Switching out argparse for click (?)

### ISSUE THREAD

**Issue by eschanet** [natliblux/nautilusocr#1]
Hi! 

I stumbled across this project by accident and think it's a really cool approach! Huge props!

While looking at the code, I noticed that you're using `argparse` to create the CLI. Any specific reason for choosing `argparse` over something like `click` (based on `optparse`)? I am personally not a huge fan of `argparse` because it can sometimes lead to unexpected behaviour due to it's automagic differentiation between arguments and options. I also think that a proper CLI built with `click` leads to much more readable code (although I agree that this might be a bit subjective, but [here](https://github.com/eschanet/simplify/blob/master/src/simplify/cli/__init__.py) is a simple example).

If you welcome contributions from others on this, I would be down to cleaning up your entrypoint a bit and introduce a proper CLI for this awesome tool. As always, feel free to close this issue in case this is not something you want to change!

Cheers,
Eric

**Comment by Schneipi** [comment]
Hi Eric,

Thanks for your nice feedback and suggestion!

So far `argparse` has served us rather well as an entrypoint, by doing what it is supposed to. We tried to emphasize readability by grouping all actions in [subparsers.py](https://github.com/natliblux/nautilusocr/blob/master/src/constants/subparsers.py). Also `click` would add yet another dependency to the project. We will stick to `argparse` for the time being. Thanks again for your input. Any other suggestions are of course welcome.

Best regards,
Pit
